# Generated by Django 4.1.4 on 2023-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopu", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totals",
            field=models.CharField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
